### ISSUE TITLE
onCustomShow只执行了一次

### ISSUE THREAD

**Issue by a2643979238** [DBAAZzz/custom-hooks-plus#1]
在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀

**Comment by a2643979238** [comment]
总不能每次跳转操作我都要去更新一下token吧

**Comment by DBAAZzz** [comment]
> 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀

正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下

**Comment by a2643979238** [comment]
![QQ_1724737018380](https://github.com/user-attachments/assets/6b7de0ee-c18c-4ab5-b6c4-80560e49cdd5)
![QQ_1724737058063](https://github.com/user-attachments/assets/8c4ed007-a266-40d3-b9d8-a783fa32f35b)
![QQ_1724737111392](https://github.com/user-attachments/assets/e16d2a9f-d087-4291-b085-b95c664b1e6f)
![QQ_1724737134118](https://github.com/user-attachments/assets/c8cd1d6f-9b41-48a9-9241-e50def040dd1)

**Comment by a2643979238** [comment]
> > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> 
> 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下

![QQ_1724737018380](https://github.com/user-attachments/assets/6b7de0ee-c18c-4ab5-b6c4-80560e49cdd5)
![QQ_1724737058063](https://github.com/user-attachments/assets/8c4ed007-a266-40d3-b9d8-a783fa32f35b)
![QQ_1724737111392](https://github.com/user-attachments/assets/e16d2a9f-d087-4291-b085-b95c664b1e6f)
![QQ_1724737134118](https://github.com/user-attachments/assets/c8cd1d6f-9b41-48a9-9241-e50def040dd1)
一步一步按照文档来操作的，APP.vue初始化，请求接口里面设置根目录下的global.ts里的token，首页使用onCustomShow监听，本来一开始打算使用pinia但是没有效果，改成了新建global.ts文件的方式来使用才有效果

**Comment by a2643979238** [comment]
> > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> 
> 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下

找到问题了，我发现只有使用uni.navigateBack返回上一页才会触发onCustomShow，而uni.reLaunch、uni.redirectTo、uni.navigateTo形式跳转的页面是不会触发onCustomShow、onCustomLoad，原生的onLoad和onShow是可以正常触发的

**Comment by DBAAZzz** [comment]
> > > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> > 
> > 
> > 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下
> 
> 找到问题了，我发现只有使用uni.navigateBack返回上一页才会触发onCustomShow，而uni.reLaunch、uni.redirectTo、uni.navigateTo形式跳转的页面是不会触发onCustomShow、onCustomLoad，原生的onLoad和onShow是可以正常触发的，该如何解决呢

现在在忙，晚上才有时间。暂时看不了你说的问题：(
正常来说执触发onCustomShow是跟uni.reLaunch这些方法是没多大联系的，你可以看下globalData的token是不是切换页面后被清掉了

**Comment by a2643979238** [comment]
> > > > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> > > 
> > > 
> > > 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下
> > 
> > 
> > 找到问题了，我发现只有使用uni.navigateBack返回上一页才会触发onCustomShow，而uni.reLaunch、uni.redirectTo、uni.navigateTo形式跳转的页面是不会触发onCustomShow、onCustomLoad，原生的onLoad和onShow是可以正常触发的，该如何解决呢
> 
> 现在在忙，晚上才有时间。暂时看不了你说的问题：( 正常来说执触发onCustomShow是跟uni.reLaunch这些方法是没多大联系的，你可以看下globalData的token是不是切换页面后被清掉了

好的，谢谢你，我已经换成了pinia的方式，反复测试了很久排查出来确实是跳转的原因造成的不执行。

**Comment by DBAAZzz** [comment]
> > > > > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> > > > 
> > > > 
> > > > 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下
> > > 
> > > 
> > > 找到问题了，我发现只有使用uni.navigateBack返回上一页才会触发onCustomShow，而uni.reLaunch、uni.redirectTo、uni.navigateTo形式跳转的页面是不会触发onCustomShow、onCustomLoad，原生的onLoad和onShow是可以正常触发的，该如何解决呢
> > 
> > 
> > 现在在忙，晚上才有时间。暂时看不了你说的问题：( 正常来说执触发onCustomShow是跟uni.reLaunch这些方法是没多大联系的，你可以看下globalData的token是不是切换页面后被清掉了
> 
> 好的，谢谢你，我已经换成了pinia的方式，反复测试了很久排查出来确实是跳转的原因造成的不执行。

你最开始不是说pinia的方式不行吗。。。谢谢你的使用。我今晚测试下是不是跳转的问题

**Comment by a2643979238** [comment]
> > > > > > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> > > > > 
> > > > > 
> > > > > 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下
> > > > 
> > > > 
> > > > 找到问题了，我发现只有使用uni.navigateBack返回上一页才会触发onCustomShow，而uni.reLaunch、uni.redirectTo、uni.navigateTo形式跳转的页面是不会触发onCustomShow、onCustomLoad，原生的onLoad和onShow是可以正常触发的，该如何解决呢
> > > 
> > > 
> > > 现在在忙，晚上才有时间。暂时看不了你说的问题：( 正常来说执触发onCustomShow是跟uni.reLaunch这些方法是没多大联系的，你可以看下globalData的token是不是切换页面后被清掉了
> > 
> > 
> > 好的，谢谢你，我已经换成了pinia的方式，反复测试了很久排查出来确实是跳转的原因造成的不执行。
> 
> 你最开始不是说pinia的方式不行吗。。。谢谢你的使用。我今晚测试下是不是跳转的问题

pinia那个问题是我Key传的方式不对已经解决了，谢谢你抽空看下

**Comment by DBAAZzz** [comment]
> > > > > > > 在APP.vue设置token后，首页onCustomShow执行一次，此时的token是有值的，如果跳转到其他页面，再从其他页面跳回首页，此时并不会触发onCustomShow，按理说此时token是有值的，应该触发onCustomShow，你文档也说了onCustomShow对应uni-app的onShow，如果只是监听token变化才调用，那onCustomShow和onCustomLoad就没区别呀
> > > > > > 
> > > > > > 
> > > > > > 正常来说是token变化一次后，onCustomShow等同于onShow会每次都执行。请问可以贴下你的代码吗，我看下
> > > > > 
> > > > > 
> > > > > 找到问题了，我发现只有使用uni.navigateBack返回上一页才会触发onCustomShow，而uni.reLaunch、uni.redirectTo、uni.navigateTo形式跳转的页面是不会触发onCustomShow、onCustomLoad，原生的onLoad和onShow是可以正常触发的，该如何解决呢
> > > > 
> > > > 
> > > > 现在在忙，晚上才有时间。暂时看不了你说的问题：( 正常来说执触发onCustomShow是跟uni.reLaunch这些方法是没多大联系的，你可以看下globalData的token是不是切换页面后被清掉了
> > > 
> > > 
> > > 好的，谢谢你，我已经换成了pinia的方式，反复测试了很久排查出来确实是跳转的原因造成的不执行。
> > 
> > 
> > 你最开始不是说pinia的方式不行吗。。。谢谢你的使用。我今晚测试下是不是跳转的问题
> 
> pinia那个问题是我Key传的方式不对已经解决了，谢谢你抽空看下

我本地测试了下，在二级页面用uni.reLaunch跳转回来，是能触发onShow和onCustomShow的
![1](https://github.com/user-attachments/assets/6bb58bde-d040-4d38-940c-963d2d2c25c1)
