### ISSUE TITLE
uni-app cli构建的小程序项目，运行打包命令打完的包，功能无法运行，似乎是没有打包进去？

### ISSUE THREAD

**Issue by a2643979238** [DBAAZzz/custom-hooks-plus#2]
dev:mp-weixin运行的小程序是正常的
build:mp-weixin 功能无法运行

**Comment by DBAAZzz** [comment]
💔晚上我验证下

**Comment by a2643979238** [comment]
> 💔晚上我验证下
我已经解决了，从store的方式，换成了你文档的新建global.ts文件的方式就可以了

**Comment by DBAAZzz** [comment]
> > 💔晚上我验证下
> > 我已经解决了，从store的方式，换成了你文档的新建global.ts文件的方式就可以了

用的版本是多少？版本1.0.4破坏性更新了监听pinia key的方式，可以看下最新的文档

**Comment by a2643979238** [comment]
> > > 💔晚上我验证下
> > > 我已经解决了，从store的方式，换成了你文档的新建global.ts文件的方式就可以了
> 
> 用的版本是多少？版本1.0.4破坏性更新了监听pinia key的方式，可以看下最新的文档

1.0.3和1.0.4,两种监听pinia的方式都试了，运行build:mp-weixin都无效。可能是我用法不对，最后还是换了另一种可以.

**Comment by DBAAZzz** [comment]
> > > > 💔晚上我验证下
> > > > 我已经解决了，从store的方式，换成了你文档的新建global.ts文件的方式就可以了
> > 
> > 
> > 用的版本是多少？版本1.0.4破坏性更新了监听pinia key的方式，可以看下最新的文档
> 
> 1.0.3和1.0.4,两种监听pinia的方式都试了，运行build:mp-weixin都无效。可能是我用法不对，最后还是换了另一种可以.

感谢提了issues，版本1.0.5已经修复了该问题。具体原因是：https://github.com/vuejs/pinia/discussions/1117
